### ISSUE TITLE
Instrumentation test failed

### ISSUE THREAD

**Issue by tprochazka** [kovmarci86/android-secure-preferences#8]
I started testing the new version and one of integration test failed, when I try to build library by maven.

``` java
[INFO] 4df1c91a0c879f8b_samsung_GT-N7100 :       ERROR:com.mkovacs.android.secure.preferences.SecureSharedPreferencesFunctionalTest#testSecureSharedPreferencesApply
[INFO] 4df1c91a0c879f8b_samsung_GT-N7100 :       java.lang.IncompatibleClassChangeError: interface not implemented
at com.mkovacs.android.secure.preferences.encryption.EncryptionHelper.encode(EncryptionHelper.java:71)
at com.mkovacs.android.secure.preferences.SecuredEditor.putBoolean(SecuredEditor.java:69)
at com.mkovacs.android.secure.preferences.SecureSharedPreferencesFunctionalTest.testSecureSharedPreferencesApply(SecureSharedPreferencesFunctionalTest.java:118)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:192)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:177)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1619)
```

**Comment by kovmarci86** [comment]
Thank you,
Added some filtering to not to call stringSet related calls on pre API 11 devices.
Can you please also test this?
I was testing with a 2.3.3 x86 emulator, 4.1 emulator, sgs4. Now it does not fail.

btw: opened a ticket for supporting string sets: Issue #9
